fs            = require 'fs'
{exec, spawn} = require 'child_process'

files = ['tf2']

task 'watch', 'compile and minify files on change', ->
  fs.watchFile("#{file}.coffee", (curr, prev) ->
    if curr.mtime > prev.mtime
      exec "coffee -cm #{file}.coffee &&
            uglifyjs --source-map #{file}.map --in-source-map #{file}.map
            -o #{file}.js #{file}.js"

      console.log "#{curr.mtime.toLocaleTimeString()
                    } - compiled #{file}.coffee"
  ) for file in files
