// Generated by CoffeeScript 1.3.3
(function() {
  var capitalize, getattributes, getdescription, hide, moveMouse, show,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  show = function(e) {
    var attributes, description, title;
    title = e.target.title;
    attributes = getattributes(e.target);
    description = getdescription(e.target);
    description = description ? '<br>' + description : description;
    hbox.innerHTML = "<div style='font-size:1.2em;color:rgb(230,230,230)'>" + title + "</div>" + attributes + description;
    return hbox.style.display = "block";
  };

  getattributes = function(item) {
    var attributes, divs;
    divs = item.getElementsByTagName('div');
    attributes = divs.length > 0 ? divs[0].innerHTML : '';
    return attributes;
  };

  getdescription = function(item) {
    var description;
    description = item.getAttribute('data-description');
    if (description == null) {
      description = '';
    }
    return description;
  };

  capitalize = function(word) {
    return word[0].toUpperCase() + word.slice(1);
  };

  hide = function() {
    return hbox.style.display = "none";
  };

  window.hideitembox = function(e) {
    var target, _ref;
    target = e.target || e.srcElement;
    if (target !== itembox && __indexOf.call(itembox.getElementsByTagName('ul'), target) < 0 && __indexOf.call(itembox.childNodes, target) < 0 && ((_ref = target.tagName) !== 'LI' && _ref !== 'A' && _ref !== 'INPUT' && _ref !== 'SELECT' && _ref !== 'OPTION' && _ref !== 'H3' && _ref !== 'IMG')) {
      return itembox.style.display = 'none';
    }
  };

  moveMouse = function(e) {
    hbox.style.top = (e.pageY + 28) + "px";
    return hbox.style.left = (e.pageX - 154) + "px";
  };

  window.openSummary = function(e) {
    return showiteminfo(e.target);
  };

  window.showiteminfo = function(element) {
    var b, blueprints, blueprintshtml, buy, buyButton, chance, classes, classeshtml, hoverarea, i, image, imageUrl, index, istoken, isweapon, itemId, itemName, j, listitem, marketprice, name, quality, re, storeprice, style, tags, tagshtml, title, wikilink, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _m, _n, _o, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    window.hbox = document.getElementById('hoverbox');
    window.itembox = document.getElementById("itembox");
    itemId = element.id;
    itemName = element.title;
    marketprice = element.getAttribute('data-marketprice');
    if (marketprice) {
      _ref = ['Unique', 'Vintage', 'Strange', 'Genuine', 'Haunted'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        re = new RegExp(i, "g");
        marketprice = marketprice.replace(/[{}']/g, '').replace(/, /g, '<br>').replace(re, "<span class='" + (i.toLowerCase()) + "'>" + i + "</span>");
      }
      marketprice = '<h3 style="margin:5px 0 5px 0">' + marketprice + '</h3>';
    } else {
      marketprice = '';
    }
    storeprice = element.getAttribute('data-storeprice');
    imageUrl = element.getAttribute('data-image');
    blueprints = element.getElementsByTagName('ul');
    blueprintshtml = '<div id="blueprints">';
    for (_j = 0, _len1 = blueprints.length; _j < _len1; _j++) {
      b = blueprints[_j];
      chance = b.getAttribute('data-chance');
      blueprintshtml += '<ul class="blueprint">';
      _ref1 = b.getElementsByTagName('li');
      for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
        i = _ref1[_k];
        for (j = _l = 0, _ref2 = i.getAttribute('data-count'); 0 <= _ref2 ? _l < _ref2 : _l > _ref2; j = 0 <= _ref2 ? ++_l : --_l) {
          name = i.title;
          index = i.id;
          style = "background-image:url(" + (i.getAttribute('data-image')) + ");";
          title = 'title="' + name + '"';
          listitem = "<li " + title + " class='item-small' style='" + style + "'></li>";
          if (index) {
            listitem = ("<a href='/item/" + index + "' target='_blank'>") + listitem + "</a>";
          }
          blueprintshtml += listitem;
        }
      }
      blueprintshtml += "<li title='Crafting Chance' style='position:relative;top: 13px;margin-left:440px;'><h3>" + chance + "%</h3></li>";
      blueprintshtml += "</ul>";
    }
    blueprintshtml += '</div>';
    if (storeprice) {
      storeprice = "$" + storeprice;
      buyButton = "<form style='position:absolute;bottom:19px;left:345px;'>" + storeprice + "<br><input type='text' value='1' size='1' id='quantity' class='textbox'></form><a href='#' id='buy-button'></a>";
    } else {
      buyButton = '';
    }
    wikilink = 'href="http://wiki.teamfortress.com/wiki/' + itemName + '"';
    classeshtml = "<div id='classes' style='position:absolute;top:0;right:0'>";
    classes = element.getAttribute('data-classes');
    if (classes) {
      _ref3 = classes.split(',');
      for (_m = 0, _len3 = _ref3.length; _m < _len3; _m++) {
        i = _ref3[_m];
        classeshtml += "<a href='/search?q=" + i + "' target='_blank'><img title='" + i + "' width='40px' height='40px' src='/images/items/" + i + "_icon.png'></a><br>";
      }
    }
    classeshtml += "</div>";
    tagshtml = "<div id='tags' style='position:absolute;top:-5px;left:-1px'>";
    tags = element.getAttribute('data-tags');
    if (tags) {
      tags = tags.split(',');
      isweapon = __indexOf.call(tags, 'weapon') >= 0;
      istoken = __indexOf.call(tags, 'token') >= 0;
      title = image = '';
      _ref4 = ['primary', 'secondary', 'melee', 'pda2'];
      for (_n = 0, _len4 = _ref4.length; _n < _len4; _n++) {
        i = _ref4[_n];
        if (__indexOf.call(tags, i) >= 0) {
          if (isweapon) {
            title = capitalize(i) + ' Weapon';
            image = i;
          } else if (istoken) {
            title = 'Slot Token';
            image = 'slot_token';
          }
        }
      }
      _ref5 = ['hat', 'misc'];
      for (_o = 0, _len5 = _ref5.length; _o < _len5; _o++) {
        i = _ref5[_o];
        if (__indexOf.call(tags, i) >= 0) {
          title = capitalize(i);
          image = i;
        }
      }
      if (istoken && classes !== null) {
        title = 'Class Token';
        image = 'class_token';
      }
      if (title && image) {
        tagshtml += "<a href='/search?q=" + title + "' target='_blank'><img title='" + title + "' width='50px' height='50px' src='/images/items/" + image + ".png'></a><br>";
      }
    }
    tagshtml += "</div>";
    itembox.innerHTML = "<h2 style='margin-bottom:5px;color:#B2B2B2;'>" + itemName + "</h2>    <a class='button' target='_blank' title='Open in Wiki' style='position:absolute;bottom:10px;left:10px;' " + wikilink + ">Wiki</a>    " + marketprice + "    <form name='tf2outpostform' method='POST' action='http://www.tf2outpost.com/search' target='_blank'>      <input type='hidden' name='has1' value='440," + itemId + ",6'>      <input class='button' style='position:absolute;bottom:10px;left:70px;margin:0;' type='submit' title='Find trades' name='submit' value='Trades'>      <input type='hidden' name='type' value='any'>      <select id='quality' class='textbox' style='text-align:left'>        <option value='6' selected=''>Unique</option>        <option value='3'>Vintage</option>        <option value='1'>Genuine</option>        <option value='5'>Unusual</option>        <option value='11'>Strange</option>        <option value='13'>Haunted</option>      </select>    </form>    " + buyButton + "    " + blueprintshtml + "    " + classeshtml + "    " + tagshtml;
    itembox.style.display = "block";
    hoverarea = document.createElement('div');
    hoverarea.title = element.title;
    hoverarea.setAttribute('data-description', getdescription(element));
    hoverarea.id = 'hoverarea';
    hoverarea.style.backgroundImage = "url('" + imageUrl + "')";
    hoverarea.innerHTML = '<div style="display:none">' + getattributes(element) + '</div>';
    hoverarea.addEventListener("mouseout", hide, false);
    hoverarea.addEventListener("mousemove", moveMouse, false);
    hoverarea.addEventListener("mouseover", show, false);
    itembox.appendChild(hoverarea);
    buy = document.getElementById('buy-button');
    if (buy) {
      buy.onclick = function() {
        var quantity;
        quantity = document.getElementById('quantity').value;
        return window.open("http://store.steampowered.com/buyitem/440/" + itemId + "/" + quantity);
      };
    }
    quality = document.tf2outpostform.quality;
    return quality.onchange = function() {
      return document.tf2outpostform.has1.value = "440," + itemId + "," + quality.value;
    };
  };

  window.onload = function() {
    var cell, i, _i, _len, _ref, _results;
    window.hbox = document.getElementById("hoverbox");
    if (hbox) {
      _ref = document.getElementsByClassName('itemlist');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        _results.push((function() {
          var _j, _len1, _ref1, _results1;
          _ref1 = i.getElementsByTagName('li');
          _results1 = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            cell = _ref1[_j];
            cell.addEventListener("mouseout", hide, false);
            cell.addEventListener("mousemove", moveMouse, false);
            cell.addEventListener("mouseover", show, false);
            _results1.push(cell.addEventListener("click", openSummary, false));
          }
          return _results1;
        })());
      }
      return _results;
    }
  };

}).call(this);
